title: Shuxin Li's Homepage
page-top-title: lishuxin
top-section-bg-text: Be what you wanna be
home-subtitle: Shuxin Li&ensp;|&ensp;李姝欣
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
